# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.


service: hob
provider:
  name: aws
  runtime: python3.6
  stage: prod
  region : us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::data-eng-cresco-labs/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-west-2:159246121673:function:cresco-lab-api-service-int-post_put"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-west-2:159246121673:function:cresco-lab-api-service-int-categorization"


functions:
  etl:
    handler: lambda_function.lambda_handler
    events:
      - schedule: cron(0 13 * * ? *)
    environment:
      SNOWFLAKE_ACCOUNT: ic98909
      NAME: ETL_LOAD_USER
      PASS: 26@Allen
      SMTP_SERVER: smtp.office365.com
      SMTP_PORT: 587
      SENDER: uploads@crescolabs.com
      PASSWORD: d:'Xy-c.7:WKa!5
      recipients: udai.shergill@crescolabs.com,micah.davidson@crescolabs.com,aaron.cole@crescolabs.com
      SQL_SERVER: '{"host":"hob-labels-prod.cjcyi9ibddks.us-east-2.rds.amazonaws.com", "user":"crescolabs", "password":"4BCd3k787UAclj2209Bnreaz82", "port":1433,"database":"hob_labels","driver":"ODBC Driver 17 for SQL Server"}'
      JOLIET: '{"host":"cresco.biotrackaws.net", "user":"rocrescojoliet", "password":"ahkeiKu7aexa", "port":5433,"database":"biotrackthc"}'
      KANKAKEE: '{"host":"cresco.biotrackaws.net", "user":"rocrescokankakee", "password":"MaiN9peyuak7", "port":5434,"database":"biotrackthc"}'
      LINCOLN: '{"host":"cresco.biotrackaws.net", "user":"rocrescolincoln", "password":"voghie9eiPh7", "port":5432,"database":"biotrackthc"}'
    layers:
      - arn:aws:lambda:us-west-2:159246121673:layer:data_engineering_pandas_sqlalchemy_v2:1
      - arn:aws:lambda:us-west-2:159246121673:layer:pyodbc:1
    memorySize: 512
    timeout: 860

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true

package:
  individually: true
  include:
    - "!./**"
    - "lambda_function.py"
    - "database.py"
    - "snow.py"
    - "mssqlserver.py"
    - "postgres.py"
    - "email_util.py"
    - "psycopg2/**"
    - "xlsxwriter/**"
    - "cresco_etl_helpers.py"

  exclude:
    - "**"
